/**:
  ros__parameters:
    min_longitudinal_offset: -1.60
    max_longitudinal_offset: 5.5
    min_lateral_offset: -1.4765
    max_lateral_offset: 1.3165
    min_height_offset: 0.0
    max_height_offset: 2.887
